### ISSUE TITLE
Molecular dynamics and stda-xTB

### ISSUE THREAD

**Issue by Vale1987** [grimme-lab/stda#10]
I am working on supramolecular cages and I tried to calculate the uv-vis and cd spectra of 
a chiral cage. The result I got of the calculated spectra was showing some extra peaks and the shifts were also slightly off. 

In one of you publications you do an MD calculation before the STDA calculation. As far as I understood you use the average of
all the calculated states of the MD trajectory and use this as an input for the STDA-xTB.

My question is: do you have any information on how to do that? Do you manually calculate the average of all the generated coordinates and use that? 
Or there is a different way to do that so I can improve the accuracy?

**Comment by mdewergi** [comment]
This is a question for Jakob. @liljay42 can you have a look?

**Comment by Cybert92** [comment]
We did not average the molecular coordinates, but the computed sTDA-xTB spectra. 

The workflow is as follows:

1. Perform your MD simulation
2. Take from the MD trajectory a certain amount of structures (we took 100 in most of our cases). These structures (snapshots) must be taken equidistantly to ensure a proper description of the ensemble.
3. Compute for each of those structures a sTDA-xTB calculation
4. Average all spectra

Maybe some bash code or hints are helpful:

for 2.:

- generate for each structure a folder
- get from the xtb trajectory (xtb.trj) your snapshots. We use a simple `sed` command, 
e.g.: `sed -n "$start,$end p" xtb.trj >> snapshots.trj`,
where `$start` and `$end` are the start/end line numbers of the snapshot in the xtb.trj file
- you can get those numbers with some simple math. The coordinates are stored as .xyz files in xtb.trj. The length of a xyz file is `number of atoms + 2`. 


for 4.:

- just merge all the tda.dat files into one file and then use this script to get a final file that can be used with `gspec`.

`#!/bin/bash`
`# This script merges multiple tda files that were just 'catted' together`
`if [ -n "$1" ]; then`
`file="$1"`
`else`
`file='tda.dat'`
`fi`
`if [ -s "$file" ]; then`
`  line=$(grep -n -m 1 'DAT' $file | sed 's/\:/ /g'|gawk '{print $1}')`
`  sed -n "1,$line p" $file > tmp.dat`
`  cat $file |gawk '{if (NF == 6) print $1,$2,$3,$4,$5,$6}'|gawk '{print NR,$2,$3,$4,$5,$6}' >> tmp.dat`
`  mv tmp.dat $file`
`else`
` echo "no $file file found"`
`fi `

- before you run `gspec`, change the `RFAKTOR` value in your final file to 1/number of snapshots, e.g. with 100 snapshots to 0.01. This is important when you are interested in absolute intensities.
