### ISSUE TITLE
Compiling with GNU compilers

### ISSUE THREAD

**Issue by shoubhikraj** [grimme-lab/stda#11]
Is it possible to compile stda with GNU compilers? The makefile assumes that the ifort compiler is present. When I try to use gcc (mingw64) with meson, it runs into compile errors. For example:
```
Error: Logicals at (1) must be compared with .eqv. instead of ==
../linear_response.f:4401:15:

 4401 |             jk=lin8(i,j)
      |               1
```
and,
```
../linear_response.f:3092:72:

 3092 |       call PrintBeta(beta)
      |                                                                        1
Error: Missing actual argument for argument 'unit' at (1)
```

How do I compile stda with gfortran, if possible?

**Comment by mdewergi** [comment]
No this is not possible. But you can use binaries that are provided here : https://github.com/grimme-lab/stda/releases
