### ISSUE TITLE
Windows build for stda

### ISSUE THREAD

**Issue by shoubhikraj** [grimme-lab/stda#14]
I am an Windows user, and I wanted to use stda on my laptop because it is very fast. Therefore, I made some changes in the source code in order to make it work. I wanted to ask if there are any plans for making a windows build of stda, and if not, is it okay if I distribute compiled Windows executables for stda as they are not available anywhere?

**Comment by mdewergi** [comment]
There is no plan for now but if you have modifications to make it works under windows, we may be interested in and as so we could distribute on our github page after testing.

**Comment by shoubhikraj** [comment]
@mdewergi I have opened a pull request #15 with the changes. The changes are very minor and only affects the printing of date and time at the beginning and end of stda run.

**Comment by mdewergi** [comment]
Thank you! I need to find someone with a windows computer and intel compiler installed to test it and then I get back to you.
