### ISSUE TITLE
Detailed output for excitation configurations upon request 

### ISSUE THREAD

**Issue by m82a1whn** [grimme-lab/stda#18]
Since **xtb4stda** can output .molden files and **stda** can output the excitation configurations ( the contribution of transition from MO a to MO b), I want to further investigate the excitation mechanism and characteristics through xTB-sTDA program. However, due to the limitation of only three MO pairs of transition that contributed most to each excited state is outputted in the program, which limit the use of MO analysis techniques in many excited states involves contributions from a wide range of excited MO pairs. Thus I wish the excitation configuration can be output in detail upon request in the command line. This should be a function easy to implement since the calculation itself goes through all the excitation configurations, all it needs to do is to write it down. Thank you!

**Comment by m82a1whn** [comment]
![excitation configuration](https://user-images.githubusercontent.com/115522342/194999613-1860c4b2-96e5-414f-86e4-6ba495b3f60b.png)
To avoid confusion, the data in the red square is the _excitation configuration_ I mentioned above, which I would like to see a more detailed output.

**Comment by cbannwarth** [comment]
You can already get that information from the `-vectm` option (see manual). 
Note that the contributions are going over the full occ*virt list (not just the reduced space used in sTDA/sTDDFT).
I hope this helps.

**Comment by m82a1whn** [comment]
thanks a lot! Much appreciated! XD

**Comment by mdewergi** [comment]
By the way, you can also use natural transition orbitals for this kind of analysis with the -nto keyword.

**Comment by m82a1whn** [comment]
> By the way, you can also use natural transition orbitals for this kind of analysis with the -nto keyword.

Thank you!

**Comment by m82a1whn** [comment]
> You can already get that information from the `-vectm` option (see manual). Note that the contributions are going over the full occ*virt list (not just the reduced space used in sTDA/sTDDFT). I hope this helps.

Does this mean, with -vectm, the #No. of MOs in the stda output fits the #No. of MOs in the .molden file via xTB process?
