### ISSUE TITLE
Correct tda settings for UV-Vis spectra

### ISSUE THREAD

**Issue by mstfoz** [grimme-lab/stda#19]
Hi,

I add UV word to the first line of tda.dat file. However, if i change the VELO keyword to MIX or if i delete this word completly it gives different spectrum naturally. I suppose length formalism is the correct one for the UV. Should I delete this keyword completly or is there any keyword for the length formalism? Thank you!

**Comment by cbannwarth** [comment]
Hey there, 
length is the one that is defaulted if you run a UV spectrum calculation. 
For RPA, it won't matter much, but for TDA length is typically used, while mixed is mostly closer to the RPA results (velocity with TDA is typically too small).

**Comment by mstfoz** [comment]
I should have mentioned that it's stda-xtb calculation. 
If so, why do i get different results with the following two inputs:

" UV
 NM
 **VELO**
 MMASS
 ...."

and

" UV
 NM
 MMASS
 ..."

**Comment by cbannwarth** [comment]
VELO specifies oscillator strengths in velocity formalism, leaving it out gives you the length form.
