### ISSUE TITLE
How many RAM?

### ISSUE THREAD

**Issue by arescifina** [grimme-lab/stda#21]
Dear Professor Grimme,
I'm using the structure reported in the zipped file, optimized at gfn2-xTB level, to calculate the UV spectrum.
After successfully obtaining the wfn.xtb file I process it with the command stda -xtb -e 10 (stda version 1.6.3 precompilated).
The process stops with the following statement:
  selecting CSF ...
  average/max PT2 energy lowering (eV): 0.007 0.236
        72145 CSF included by PT.
       110188 CSF in total.
  calculating TDA matrix ...
Killed

I think it's a RAM problem (I have 64 GB) since just before the job was killed the RAM exceeds 99%.
Would it be possible to know in advance how much RAM is needed?
Could this be worked around by using up disk space or creating a larger swap buffer?
Thanks for the attention.
Kind regards,
Antonio Rescifina
[2rGO-7_TPP.zip](https://github.com/grimme-lab/stda/files/14342909/2rGO-7_TPP.zip)

**Comment by mdewergi** [comment]
Dear Antonio,
You use a large energy threshold of 10 eV for your calculation. This energy threshold is related to the number of CSFs you have for the calculation, here 110188. So the A matrix of 110188^2 is generated and will be diagonalized. This is very big and for such calculation (with such large systems) you might need large memory node.
Thus, I can advice you to decrease the energy threshold to a number manageable by your computer. 
You can also use the read and write version of stda with the keyword -rw to use only more or less half of the memory.
Best wishes,
Marc de Wergifosse

**Comment by arescifina** [comment]
Dear Marc,
Thanks much.
I resolved with the symultaneous use of 8 eV and -rw keyword.
Kind regards,
Antonio Rescifina

**Comment by arescifina** [comment]
Dear Marc,

Thanks much.

I solved it with the simultaneous use of the 8 eV and -rw keywords.

Best regards,

Antonio Rescifina

 

 

Da: Marc de Wergifosse ***@***.***> 
Inviato: martedì 20 febbraio 2024 11:49
A: grimme-lab/stda ***@***.***>
Cc: arescifina ***@***.***>; Author ***@***.***>
Oggetto: Re: [grimme-lab/stda] How many RAM? (Issue #21)

 

Dear Antonio,
You use a large energy threshold of 10 eV for your calculation. This energy threshold is related to the number of CSFs you have for the calculation, here 110188. So the A matrix of 110188^2 is generated and will be diagonalized. This is very big and for such calculation (with such large systems) you might need large memory node.
Thus, I can advice you to decrease the energy threshold to a number manageable by your computer.
You can also use the read and write version of stda with the keyword -rw to use only more or less half of the memory.
Best wishes,
Marc de Wergifosse
