### ISSUE TITLE
Allocation for qkj/bmat crasehd

### ISSUE THREAD

**Issue by Sanarmy** [grimme-lab/stda#23]
I have this error when i run a cluster of 8 anthracene molecules. The orbitals of this cluster are obtained using Gaussian, B3LYP/6-31G**, and i use g2molden with doble precision to obtain the molden input. This molden input works in molden so the problem is not there in principle, Anyone knows why is happening to me? Is the first time that this program shows this problem to me. Thank you in advance.

I run the program:
stda -f molden.input -ax 0.25 -e 100 -sty 3 -vectm 800 > B3LYP.stda

**Comment by cbannwarth** [comment]
It will almost certainly be a memory issue - you are asking for all excitations up to 100 eV for this system. 
For this system/basis set, you are about to set up 640k * 640k large A matrix. Not even counting any other intermediate allocated by stda, that already requires more than 20 GB of memory.
If you reduce the excitation energy window to something more reasonable for UV/Vis excitations (<10 eV) & it should work.

**Comment by Sanarmy** [comment]
The problem is that i'm using a elevate -e because i need that the program take account the full MO for the calculation of the excitation coeficients (ciss_a).

**Comment by mdewergi** [comment]
If you want to use stda this way, you need more memory on the computer node. This is the only way. Or you can try the -rw option that should cut memory usage by 2. Either way, it is counterproductive to use stda with a large energy threshold. It is not designed for that.

**Comment by Sanarmy** [comment]
Okey i will try -rw. Thank you. The issue is solved.
