### ISSUE TITLE
missing parameter file?

### ISSUE THREAD

**Issue by LiamWilbraham** [grimme-lab/stda#4]
Hi, 

I may just be missing something but is the `.param_stda1.xtb` file missing from the repo? `xtb4stda` throws an error as it is not able to locate the file. Here is an example of the tail of the output :
```
 xtb4stdahome directory:/home/liam/software/stda/


 name of molecule           :
 comment line               :
 number of atoms            :     3
 number of electrons        :     8
 charge                     :  0
 spin                       : 0.0
 first test random number   :  0.7644
 parameter file /home/liam/software/stda/.param_stda1.xtb not found!
```

**Comment by mdewergi** [comment]
Hi, you should declare xtb4stdahome variable pointing to the xtb4stda directory and not stda one.

**Comment by LiamWilbraham** [comment]
After making this change I'm still getting the same issue. 

environment variables: 
```
#xtb
export PATH="$PATH:$HOME/software/xtb_6.2.2/bin"
export XTBHOME="/home/liam/software/xtb_6.2.2"
export MKL_NUM_THREADS=1
export OMP_THREAD_LIMIT=1
export OMP_NUM_THREADS=${OMP_THREAD_LIMIT},1
export OMP_STACKSIZE=500m
ulimit -s unlimited

#stda & xtb4stda
export PATH="$PATH:$HOME/software/xtb4stda"
export XTB4STDAHOME="/home/liam/software/xtb4stda"

export PATH="$PATH:$HOME/software/stda"
export STDAHOME="/home/liam/software/stda"
```

command:
`xtb4stda h2o.xyz`

result:
```
xtb4stdahome directory:/home/liam/software/xtb4stda/


 name of molecule           :
 comment line               :
 number of atoms            :     3
 number of electrons        :     8
 charge                     :  0
 spin                       : 0.0
 first test random number   :  0.0206
 parameter file /home/liam/software/xtb4stda/.param_stda1.xtb not found!
```

**Comment by mdewergi** [comment]
Parameter files are normally in it. If they are not, you can add them manually from the https://github.com/grimme-lab/xtb4stda page.
Best wishes
Marc

**Comment by LiamWilbraham** [comment]
Hi Marc, 
thanks, that's working now. In case it's useful, the download I used that caused the issue was the one from the [release page](https://github.com/grimme-lab/stda/releases/tag/v1.6.1).

**Comment by mdewergi** [comment]
Oh yes you are right parameters are missing there. I will add a note.
