### ISSUE TITLE
How can I make the sTDA program recognize the wavelength file？

### ISSUE THREAD

**Issue by doublezhang17** [grimme-lab/stda#6]
Hi，
I'm sorry that my English is not very good.
I tried to use the -resp parameter to calculate the SHG, but it only gave me a result of “infinity”. It didn't read my wavelength file. Is it because I put it in the wrong place?
   The version I use is the release version of sTDA. Only 1000 in the the wavelength file because I want to know the SHG response at 1000nm.
   Thank you very much!

**Comment by mdewergi** [comment]
Hi,
You should use -resp followed by the number of wavelengths you have in your file. For example, -resp 6 if you have 6 wavelengths in your wavelength file. The file needs to be located where you are doing your calculation with your molden or xtb input file.

Hope this will sort out your problem.

Best wishes,
Marc

**Comment by doublezhang17** [comment]
Oh, Thank you,So that’s how it is!
I also have another problem. Is it correct that I use -2pa 100 to calculate the two-photon absorption? How can I get the two-photon absorption cross section I want from the generated 2PA-abs file?

Thank you for your answer.

**Comment by mdewergi** [comment]
I will not advise you to use 2PA with sTD-DFT I am still working on this part and results are of mix quality and can be completely wrong. This is due to some simplified approximations. We are actually working to improve and make it works correctly but this will take time. So please do not use it in this state.
Best wishes,
Marc

**Comment by doublezhang17** [comment]
T_T，Then I can only use the ancient zindo method to study 2pa。
Thank you for your patient answer.  Looking forward to better progress in the sTDA method!

Zhang
