### ISSUE TITLE
MO norm error

### ISSUE THREAD

**Issue by spheex** [grimme-lab/stda#8]
Hi,

I converted my Gaussian output file into molden input file using the indications from the manual.
It worked fine!

Here is the route I used:

#P gfinput pop=full CAM-B3LYP/6-31+G(d,p) 6D 10F

However, when running this command:

`stda -f cam-b3lyp.molden.inp -ax 0.38 -be 1.86 -al 0.9 -e 7 -sty 3 -rpa > output`

The program starts, bu suddenly stops and displays:

**internal MO norm error**

Apart from the coordinates, the output file contains this:

```
 interpreted GTO in TERACHEM/GAUSSIAN style
  ...normalize GTO contractions...normalizing...done!

 # atoms          =   78
 # mos            =  949
 # primitive  aos = 1546
 # contracted aos =  950

 spherical AO basis
======================================================================
                    A O   I N T E G R A L S
======================================================================
 memory needed for AO int data:  34 Mb
 done.

 Skipping input check...
 Assuming TERACHEM style (-sty 3)

Restricted MOs found... RKS-sTD-DFT will be performed

======================================================================
                    s T D A
======================================================================
 spectral range up to (eV)     :    7.00000000000000
 occ MO cut-off (eV)           :   -18.3262054368483
 virtMO cut-off (eV)           :    10.1938109008053
 perturbation thr              :   1.000000000000000E-004
 triplet                       :  F
 MOs in TDA :          250
 oMOs in TDA:           72
 vMOs in TDA:          178
 sorting MOs ...
 reading and transforming R..V..L AO ints ...
 ints done.
 S^1/2 ...
 S^1/2 orthogonalized MO coefficients done.
 MO norm          75   2.58866821875750
```

Is it a know error? What can I do to make it work? 

Thank you in advance.
Have a nice day.

**Comment by mdewergi** [comment]
Hi 
Could you try to run stda with the  "-chk" flag  and see what it is giving to you? This will verify what -sty flag you may use.
This error means that your norm from the basis set is not right with -sty 3 option but it may be OK with others.
If this is not working, can you send me your output from gaussian, I will have a look.
Best wishes
Marc

**Comment by spheex** [comment]
Hi.
Thank you for the quick answer.

I did the "-chk" option and it gave this:

```
======================================================================
                    I N P U T   C H E C K
======================================================================
 Mulliken population correct
        290.000083 vs.         290.000000


  --- S U C C E S S ---

  GTO/MO data matches MOLPRO style
  use "-sty 2" flag in the future
```

So I used the option "-sty 2" (as well as "-sty 1"), but it gives me the same error.

To be certain that the program compilation is fine, I performed the calculation on the water example from the manual. It worked perfectly.

I also performed an another test. Previously, I used the 6-31+G(d,p) basis set. I performed the same calculation without the "+" and then run stda. It worked! So it seems that the problem comes from the basis set.

Do you want my Gaussian outputs?

Have a nice day.

**Comment by spheex** [comment]
I performed another test. I tried the TZVP basis set, as the water example from the manual, for my system. It does not work either.

I opened the molden input in Molden, and it gives me the opportunity to display the density mode. However, for my system with the basis set 6-311+G(d,p) and TZVP, it does not. But it does with the 6-311G(d,p).

It seems that the origin of the issue arises from the conversion of the Gaussian output into the molden input.

**Comment by cbannwarth** [comment]
Hi, 
would it be possible to share the Gaussian output and the molden files?
I would assume a formatting error (e.g., two floating numbers concatenated in the Gaussian output).
Thank you!
Christoph

**Comment by spheex** [comment]
I tried to upload both Gaussian and molden files, but they are too heavy.

Here is a dropbox link to the folder. It contains my system which does not work (with 6-31+G(d,p)) and the one that works (6-31G(d,p)).

If you are not confident about the link, I can try to upload files one by one here.

https://www.dropbox.com/sh/zni1k50cbdy8def/AAAqiLnNDpQxp5yr-h2oRhSNa?dl=0

**Comment by mdewergi** [comment]
I have found in your gaussian output concatenated numbers in lines 55499 and 67221 by simply searching for "0-" in the file. The norm is still not ok correcting them so I guess they should be other ones that jam the process. Thus, the problem is how gaussian formats its numbers.

**Comment by spheex** [comment]
Oh, I see... I can't really code myself, but could it be corrected into the g2molden program?
I don't know how nor where the code reads that part of the Gaussian output, but if it read a specific amount of character for each column, it could work, right? Something like in PDB format where x coordinates range from character x to x+5?
Or is it already working this way?

Or would it be easier to add an empty column between each column to separate the "0" from the "-" ?

I do not know if I'm clear in my thinking...

Anyway, thank you already for your work!

**Comment by mdewergi** [comment]
@cbannwarth Do you think this is possible?

**Comment by spheex** [comment]
I managed to make available the density mode in molden.

I did:

`sed -e "s/[0-9]-/[0-9] -/g doesnotwork.inp > test_sep.inp`

And then tried again with stda, but it still does not work.

**Comment by spheex** [comment]
I'm looking closer to the problem.

I found each values displayed at line 55499 of 'doesnotwork.log' in the 'doesnotwork.inp' except the this one '-106.47796'.
In the molden file, it appears as '************'!

I modified the Gaussian log file to add a space between such pattern "0-":

```
array=(0- 1- 2- 3- 4- 5- 6- 7- 8- 9-)
for i in ${array[@]} ; do echo $i ; var1=$(echo $i | cut -f1 -d-) ; echo $var1 ; sed -i "s/$i/${var1} -/g" doesnotwork.log ; done
```

And ran g2molden again, but it stills displays '************'.

So I think that g2molden is not able to take values of more than 3 characters like -106.XXXXX

**Comment by spheex** [comment]
Guys! 

With the help of a colleague, we managed to 'solve' the problem in g2molden!
We added a variable at the top of 'main.f':

`      character(len = 12) :: test`
and also change the loop from: 
```
! now print out a set of 5 MOs

           do j=1,5
            write(*,*)'Sym= ',ityp(j)
            write(*,*)'Ene= ',eval(j)
            write(*,'(A)')' Spin= Alpha'
            write(*,*)'Occup= ',real(iocc(j))
            do k=1,nbf
             write(*,'(i6)',advance='no')k
             write(test,'(f12.8)')coeff(k,j)
             write(*,*)" "//test
            enddo

           enddo
```
to
```
! now print out a set of 5 MOs

           do j=1,5
            write(*,*)'Sym= ',ityp(j)
            write(*,*)'Ene= ',eval(j)
            write(*,'(A)')' Spin= Alpha'
            write(*,*)'Occup= ',real(iocc(j))
            do k=1,nbf
             write(*,'(i6)',advance='no')k
             !write(*,'(f11.6)'),k,j
             write(test,'(f11.6)')coeff(k,j)
             write(*,*)" "//test
            enddo

           enddo
```
And we also reduced the number of decimals.

Now stda is working!

**Comment by mdewergi** [comment]
Ok you were faster than us!
@cbannwarth Do you want to adapt your program or should I do it?

**Comment by cbannwarth** [comment]
That's what happens when you work with a time shift :)
@mdewergi I changed it.

**Comment by mdewergi** [comment]
Great issue closed
