### ISSUE TITLE
About section link broken

### ISSUE THREAD

**Issue by Zymergen-jvandezande** [grimme-lab/stda#9]
The link in the about section is broken. This may be due to needing to login, as https://www.chemie.uni-bonn.de/pctc/mulliken-center/grimme/software/ requires a login, while appending [stda](https://www.chemie.uni-bonn.de/pctc/mulliken-center/grimme/software/stda) says that the page does not exist.

**Comment by mdewergi** [comment]
The link should be https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/stda/stda .
But now, it is more proper to refer to this github page.
What do you mean by the about section?

**Comment by Zymergen-jvandezande** [comment]
The about section on the Github page (and that on the xtb4stda page as well).

![Screen Shot 2020-12-22 at 10 04 13 AM](https://user-images.githubusercontent.com/72506564/102902479-0e631380-443d-11eb-8169-766219980d21.png)

**Comment by mdewergi** [comment]
OK I see. I do not have the access to correct this. @awvwgk can you correct this? Many thanks

**Comment by awvwgk** [comment]
Seems like the university IT team finally fixed the bug in the web interface, which allowed to insert arbitrary paths in the URL... too sad.

I could take down the link completely, if the GitHub repo is now the main resource for `stda` and `xtb4stda`, of course.

**Comment by mdewergi** [comment]
Yes  take it down seems the best option here 😉

**Comment by awvwgk** [comment]
Done.
